name: salon_repository
description: Repository for managing salons and freelancers
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_storage: ^12.4.3
  cloud_firestore: ^5.6.4
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0